### ISSUE TITLE
[BUG] Extension crashes when used locally, with Remote SSH

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#5]
**Describe the bug**
When using the extension with the Remote SSH extension, the extension fails to start 5 times in a row before shutting itself down.

**To Reproduce**
1. Download the Remote SSH extension
2. Use it to connect to a remote server via SSH (CentOS 7 was used in this instance)
3. After connecting, tell the remote instance to install the MVON# Developer Extension
4. See error in MVON# Server Output channel.

**Expected behavior**
Expectation is that the extension should install and run properly as not much should separate the remote environment from a local/host environment with the extension loaded and running in VS Code there, which we know works.

**Screenshots**
N/A - On a proprietary system.

**Versions of applicable software**
* Host OS: Windows 10
* Remote OS: CentOS 7
* Extension: Remote SSH on Host, MVON# Developer Extension on Remote
* IDE: VS Code (latest stable release)

**Code samples and/or reproduceable test cases**
Here is the error output:

```
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/home/mikew/.vscode-server/extensions/ongroup.mvon-1.93.0/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Server.<anonymous> (/home/mikew/.vscode-server/extensions/ongroup.mvon-1.93.0/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at Server.emit (events.js:182:13)
    at Pipe.onconnection (net.js:1551:8)
```

**Additional context**
A first reported use issue, huzzah! 🎊 🎈 🎉

**Comment by itsxallwater** [comment]
Hold the phone, this seems to also be an issue locally too.

```internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'c:\Users\mikew\.vscode\extensions\ongroup.mvon-1.93.0\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Server.<anonymous> (C:\Users\mikew\.vscode\extensions\ongroup.mvon-1.93.0\client\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at Server.emit (events.js:182:13)
    at Pipe.onconnection (net.js:1551:8)
```

**Comment by itsxallwater** [comment]
Follow up note: running the extension from source seems to work fine. At this point it would be good to have someone else verify the existence of the error in their environment. For what it's worth, I did try removing and reinstalling already.

**Comment by itsxallwater** [comment]
No repro on this, closing the ticket.
